name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test using Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test